---
version: "3.9"
services:
  db:
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'bgwriter_lru_maxpages=0' -c 'client_min_messages=warning'"
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
      - ./db/script:/script:ro
    restart: always
    ports:
      - 5432:5432
  backend:
    image: eu.gcr.io/akvo-lumen/idh-idc/backend:latest
    volumes:
      - ./backend:/app:delegated
    working_dir: /app
    command: ["./check.sh"]
    environment:
      - DATABASE_URL=postgresql://idc:password@db:5432/idh_idc
    depends_on:
      - db
volumes:
  pg-data:
